### ISSUE TITLE
[PROTOTYPE][PLUTONIUM] "ERROR: Weapon index mismatch for 'satchel_charge'" while joining plutionium server.

### ISSUE THREAD

**Issue by Xenolphthalein** [JBShady/COD5-Remastered#3]
Hello!

First of all: Thanks for the mods, they are great!

I am the admin of zocken.io and just updated all * - Remastered maps.
If i now want to join prototype with plutoniums client, i get the following error:
![image](https://github.com/JBShady/COD5-Remastered/assets/21215869/547010f7-5988-4303-b0fd-f10a995a2cab)

Here is a part of the log file from the plutionium client console:
```log
File Handles:
----------------------
83602 files in iwd files
Setting state to CA_LOADING in CL_DownloadsComplete
Setting state to CA_LOADING in CL_InitCGame
Player 0 no longer burning at time: 0
Player 0 no longer electrified at time: 0
Player 0 no longer transporter sick at time: 0
Error: Could not load xmodel "viewmodel_knife_bowie".
Error: Could not load material "nightvision_overlay_goggles".
Error: Could not load material "ammo_counter_tesla".
Error: Could not load material "decode_characters".
Error: Could not load material "decode_characters_glow".
Error: Could not load material "killicondied".
Error: Could not load material "killiconcrush".
Error: Could not load material "killiconfalling".
Error: Could not load material "killiconsuicide".
Error: Could not load material "killiconheadshot".
Error: Could not load material "killiconmelee".
Notetrack-to-Sound: Weapon 'falling_hands' has bad entry; notetrack 'hideTags' doesn't have a corresponding sound.
Notetrack-to-Sound: Weapon 'molotov' has bad entry; notetrack 'hideTags' doesn't have a corresponding sound.
Error: Could not load xmodel "viewmodel_zombie_type100_smg".
Error: Could not load xmodel "viewmodel_satchel_charge".
Error: Could not load xmodel "weapon_satchel_charge".
Error: Could not load material "hud_icon_satchelcharge".
Database: Assets Sync Started
Database: Assets Sync Finished
********************
ERROR: Weapon index mismatch for 'satchel_charge'
********************
```

On the server side i can see the login and the instant disconnect, but no errors.
Server address is zn01.zocken.io:28668 and can be found in the plutonium launcher.

Any idea whats happening here?

**Comment by JBShady** [comment]
These errors suggest the mod is installed incorrectly. Or plutonium has now broken certain mod support on servers. An index mismatch means that the file on the server is different than the client. I would delete all your local mod files and when you try to join let the game redownload the mod.

**Comment by Xenolphthalein** [comment]
Thanks for your quick reply!

I deleted Plutonium locally and reinstalled it (cleaning the appdata folders and everything manually) but it still does not work. After downloading the mod with plutonium it still gives me the same error message. 

Starting the game manually from the mod files (as intended) i can play without any problems.

I'll try to further debug the problem and will eventually talk to the plutionium guys directly.

Can we leave this issue open until a solution is found (either by me, you, or pluto)?

**Comment by JBShady** [comment]
I was able to get a server with the mod working. Make sure the path to your mods goes something like this "mods\nazi_zombie_remastered\mod.ff" with the mod.ff and .iwd in the last folder. I'm going to clear these issues because it all seems to be stemming from some server configuration or installation, these errors all have to do with the game not being able to find the proper assets. However, I did notice an issue where when the game ends the server just quits and doesn't show the leaderboard I just get sent back to the main menu. Have you ever noticed this? Sadly I don't have much time to debug this because I think it's just how Plutonium works with overwriting a bunch of player/lobby related gsc functions to make the join mid-game/servers work, while this was mod was designed to keep those functions like how Vanilla lobbies/servers work.

![image](https://github.com/JBShady/COD5-Remastered/assets/45800460/7aa46f28-1d1b-4c08-b816-bdc2712fca92)
